name: Trigger Netlify Build
on:
  schedule:
    # Every day at midnight
    - cron: '0 0 * * *'
workflow_dispatch:
  inputs: {}
jobs:
  build:
    name: Netlify Build
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -s -X POST -d {} "https://api.netlify.com/build_hooks/${TOKEN}"
        env:
          TOKEN: ${{ secrets.NETLIFY_CRON_BUILD_HOOK }}